## 회귀모델 사용
- y(label, 종속변수, target)가 연속형일 때 사용

In [2]:
import sklearn as sk

### 데이터 수집

In [3]:
from sklearn import datasets

# from diabetes
load_diabetes = datasets.load_diabetes()    # 인디언 당뇨 상황 조사
load_diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [4]:
# feature datas
type(load_diabetes['data']), load_diabetes['data'].shape

(numpy.ndarray, (442, 10))

In [5]:
# label data
type(load_diabetes['target']), load_diabetes['target'].shape, load_diabetes['target'].dtype

(numpy.ndarray, (442,), dtype('float64'))

In [6]:
# feature names
type(load_diabetes['feature_names']), load_diabetes['feature_names'], len(load_diabetes['feature_names'])

(list, ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], 10)

In [7]:
print(load_diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

### 데이터 전처리
- 결측치와 이상치 처리
- 데이터셋 분할(학습용도와 검증용도)

In [8]:
import pandas as pd

In [9]:
# feature 처리
df_diabetes = pd.DataFrame(data=load_diabetes['data']
             , columns=load_diabetes['feature_names'])
df_diabetes.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930

In [10]:
# label 처리
df_diabetes['MeasureValue'] = load_diabetes['target']

In [11]:
df_diabetes.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  MeasureValue  
0 -0.002592  0.019907 -0.017646         151.0  
1 -0.039493 -0.068332 -0.092204          75.0  
2 -0.002592  0.002861 -0.025930         141.0

In [12]:
df_diabetes.shape

(442, 11)

In [13]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           442 non-null    float64
 1   sex           442 non-null    float64
 2   bmi           442 non-null    float64
 3   bp            442 non-null    float64
 4   s1            442 non-null    float64
 5   s2            442 non-null    float64
 6   s3            442 non-null    float64
 7   s4            442 non-null    float64
 8   s5            442 non-null    float64
 9   s6            442 non-null    float64
 10  MeasureValue  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


In [14]:
# 학습용도와 검증용도 분할

### 데이터 학습 과정

In [15]:
from sklearn.linear_model import LinearRegression
linearRegression = LinearRegression()
linearRegression

LinearRegression()

In [16]:
df_age_sex = df_diabetes[['age', 'sex']]
df_age_sex.head(3)

age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680

In [17]:
# dataFrame 방식
linearRegression.fit(X=df_age_sex, y=load_diabetes['target'])

LinearRegression()

In [18]:
linearRegression.coef_, linearRegression.intercept_
# y^ = (301.16135996 * 0.038076) + (17.3924542 * 0.050680) + 152.13348416289594

(array([301.16135996,  17.3924542 ]), 152.13348416289594)

In [19]:
predict = linearRegression.predict(df_age_sex[:1])    # 0.038076	0.050680 -> y^
source = load_diabetes['target'][:1]
predict, source

(array([164.48192757]), array([151.]))

In [20]:
(301.16135996 * 0.038076) + (17.3924542 * 0.050680) + 152.13348416289594

164.4819536835889

In [25]:
# type(df_age_sex[:1])
df_age_sex[:1]

age      sex
0  0.038076  0.05068

In [27]:
df_age_sex[:1].values, df_age_sex[:1].values.shape

(array([[0.03807591, 0.05068012]]), (1, 2))

### 모델 배포

In [22]:
# 인스턴스화 되어 있는 것을 파일 저장
import pickle

In [23]:
save_file_name = '../../files/03.LinearRegression_deployments_diabetes.pkl'

with open(save_file_name, 'wb') as save_file:
    pickle.dump(linearRegression, save_file)
    pass